version: '3.8'

services:
  web:
    build: . # Usa o seu Dockerfile
    # Inicia o servidor Rails, ignorando o banco de dados por enquanto
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails # Mapeia sua pasta de código para /rails (coerente com Dockerfile)
    ports:
      - "3000:3000"
    # Remova a seção 'depends_on: - db' se quiser
