services:
  web:
    build: .
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment: # <-- Adicione esta seção
      RAILS_ENV: test
      # Chave falsa para testes, o Rails exige para inicializar
      SECRET_KEY_BASE: 'dummy_secret_for_tests'
      BUNDLE_WITHOUT: 'production'
